### PR TITLE
turn off auditing for an instance of dbcontext

### PR DESCRIPTION
**Pull request by mgildea**
added property public bool AuditChanges to TrackerContext class. This is set to true in each constructor.  This allows an instance of a dbcontext to set the AuditChanges property to false in order to turn on and off auditing when necessary.

### CODE REVIEW

**Comment by bilal-fazlani** [comment]
lets merge this to master. could you please ad some unit tests ?

**Comment by mgildea** [comment]
Ya I'll look at that in the morning. Thanks,

Matt

**Comment by mgildea** [comment]
I will aslo add this to the SaveChangesAsync and Identity project

**Comment by bilal-fazlani** [comment]
okay cool

**Comment by bilal-fazlani** [comment]
This feature has been implemented

**Comment by mgildea** [comment]
where is this feature implemented?  How can I turn off auditing for an instance of a dbcontext with the current project?

I never put together unit tests for this.  I have implemented this in a cleaner way in my local project. I can put together some unit tests and create a pull request if still needed.

**Comment by bilal-fazlani** [comment]
Just see if this is what you are looking for ?

https://github.com/bilal-fazlani/tracker-enabled-dbcontext/wiki#at-what-levels-can-tracking-be-configured-

**Comment by bilal-fazlani** [comment]
On a second thought, it makes sense to enable or disable tracking on an instance of dbcontext. add the unit tests to this pull request and we will incorporate your changes.

**Comment by mgildea** [comment]
I don't think this is quite what i'm looking for...I would like to be able to open a dbcontext and have changes not be tracked for a single instance of a dbcontext not necessarily the entire application....

so i could have the following code segments inline:

using(var ctx = new ApplicationDbContext())
{
ctx.IsAuditingEnabled = false;
//auditing here is disabled
....
}

using(var ctx = new ApplicationDbContext())
{
//auditing here is enabled by default
....
}

You can keep this pull request closed and I can issue a new one; i think i have a little better implementation that what i previously submitted.

**Comment by bilal-fazlani** [comment]
yeah. just create a new pull request if it easier. just make sure u have some unit tests.

**Comment by bilal-fazlani** [comment]
I am closing this pull request. create a new one.

**Pull request closed without merging**
