### PR TITLE
EF Core 2 support

### PR DESCRIPTION
**Pull request by asulwer**
rearranged projects to include support for EF Core 2
moved common code into a shared project
renamed EF6 projects to indicated EF6 code
created EF Core projects with code changed to support EF Core 2

major projects rearrangement to support EF Core, code changes exist in EF Core projects

### CODE REVIEW

**Comment by bilal-fazlani** [comment]
Finally someone is moving it to .net core. Thanks @asulwer . This is looks like big change. Will take a look in next few days. 

We might need to release it as a separate nuget package though. Just like ef core is a separate nuget package from ef.

**Comment by asulwer** [comment]
I created a web project to test the two components. I am in the process of creating actuals test projects for the various components.  maybe this weekend I can post some.

**Comment by asulwer** [comment]
forgot to mention. I am using an IsDeleted for soft deleting a model.  I am not using it the way you initially had in mind.  this property is not exposed at the model level but added programmatically.  your package dies if a property exists but isn't specifically declared in the model.  check out my change in TrackerEnabledDbContext.Common.Configuration.PropertyConfigValueFactory.  look at SampleLogMakerCoreContext and how I am implementing IsDeleted for soft deleting.

**Comment by chrisrrowland** [comment]
Was there a separate nuget package created or this?

**Comment by asulwer** [comment]
no there was not.  I am still working on this port.  It is working but beta

**Comment by asulwer** [comment]
anyone looking at this - its ready and I am using it in a production environment.  it will require a manual merge as it is a complete restructure of the parent project.  it works for EF Core 2 and I am updating it to support EF Core 2.1 too

**Comment by bilal-fazlani** [comment]
@asulwer 
would you be able to merge this by resolving conflicts? Do I need to give you any permissions ?

**Comment by asulwer** [comment]
the conflicts are mostly because of solution rearrangement.  the conflict files are still there but, I think, better organized to separate EF6 & Core functionality.  if you want to elevate my privileges so I can merge that would be great!

**Comment by asulwer** [comment]
I have manually merged the two other pull requests into my branch.  I have also completely separated all EF6 projects out of mine. So this is no longer a fork anymore but a completely separate project.  strictly Core code.  Please look over what I have before I spin off.  I need to be sure that I have recognized your considerable contributions

**Pull request closed without merging**
