### PR TITLE
Extended identity db context

### PR DESCRIPTION
**Pull request by gradu-kpmg**
I use Asp.NET Identity with completely customized entity classes, which requires the TrackerIdentityContext<TUser, TRole, TKey, TUserLogin, TUserRole, TUserClaim> generic form (as well as the existing TrackerIdentityContext<TUser>). A simple change to the way TrackerIdentityContext inherits from IdentityDbContext allows achieving this with no changes to the functionality whatsoever.

### CODE REVIEW

**Comment by bilal-fazlani** [comment]
Hi, are all the unit tests passing after your change ? If yes, lets merge this to master. let me know

**Comment by gradu-kpmg** [comment]
Hi, yes all good!

image

**Comment by redwyre** [comment]
Any idea when this change will make its way to a nuget release?

**Comment by bilal-fazlani** [comment]
Just looking at your code and trying to understand the change.
Will get back to you shortly.




On Thu, Sep 10, 2015 at 12:06 PM, Simon <notifications@github.com> wrote:

> Any idea when this change will make its way to a nuget release?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bilal-fazlani/tracker-enabled-dbcontext/pull/46#issuecomment-139130534>
> .
>



-- 














Thanks & regards

*Bilal Fazlani*

**Comment by ChocoMachine** [comment]
Hi Bilal,

 

There is a lot  of legacy code in the repository. The new project is stored in CHO.ALL, which currently contains the reference architecture. This will be the solution I want to add release management for.

 

Thank you.

 

  David Manning

**Comment by bilal-fazlani** [comment]
Hi David,
I am bit confused. Where is this CHO.ALL ?
I would like to see this reference architecture please.

On Fri, Sep 11, 2015 at 3:45 AM, David <notifications@github.com> wrote:

> Hi Bilal,
>
>
>
> There is a lot of legacy code in the repository. The new project is stored
> in CHO.ALL, which currently contains the reference architecture. This will
> be the solution I want to add release management for.
>
>
>
> Thank you.
>
>
>
> David Manning
>
>
>
>
>
>
>
> From: Bilal [mailto:notifications@github.com]
> Sent: Thursday, 10 September 2015 7:22 PM
> To: bilal-fazlani/tracker-enabled-dbcontext <
> tracker-enabled-dbcontext@noreply.github.com>
> Subject: Re: [tracker-enabled-dbcontext] Extended identity db context (#46)
>
>
>
> Just looking at your code and trying to understand the change.
> Will get back to you shortly.
>
>
>
>
> On Thu, Sep 10, 2015 at 12:06 PM, Simon <notifications@github.com <mailto:
> notifications@github.com> > wrote:
>
> > Any idea when this change will make its way to a nuget release?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/bilal-fazlani/tracker-enabled-dbcontext/pull/46#issuecomment-139130534
> >
> > .
> >
>
>
>
> --
>
>
>
>
>
>
>
>
>
>
>
>
>
>
> Thanks & regards
>
> *Bilal Fazlani*
>
>
>
> —
> Reply to this email directly or view it on GitHub <
> https://github.com/bilal-fazlani/tracker-enabled-dbcontext/pull/46#issuecomment-139179942>
> . <
> https://github.com/notifications/beacon/AHmiukAK9MBzCWhuCM834O2Hiol8y4iVks5owUNHgaJpZM4FswTg.gif>
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bilal-fazlani/tracker-enabled-dbcontext/pull/46#issuecomment-139397737>
> .
>



-- 














Thanks & regards

*Bilal Fazlani*

**Comment by ChocoMachine** [comment]
Hi,

 

Sorry, I got confused with my emails. Ignore that one.

 

Sorry.

 

  David.

**Pull request merged**
