### PR TITLE
Update to Model to address Issue #79 with MySQL

### PR DESCRIPTION
**Pull request by StuartFerguson**

### CODE REVIEW

**Comment by StuartFerguson** [comment]
Just ran some tests this morning on SQL Server and the only difference is the EventDateUTC column data is updated from '17/12/2015 09:21:33 +00:00' to '17/12/2015 09:21:33'.

**Comment by bilal-fazlani** [comment]
Awsome :+1:

**Comment by StuartFerguson** [comment]
Can you confirm when this update will be included in a release?

**Comment by bilal-fazlani** [comment]
As soon as I get some free time.  3 days approx

**Pull request merged**
