### PR TITLE
Updated Audit entities keys to long instead of int

### PR DESCRIPTION
**Pull request by gradu-kpmg**
Depending on level of use and size of database, running out of int values for the audit tables is a distinct possibility. I want to integrate this with an application where we have a 7 year data/log retention period, so running out of keys is highly likely and a risk I cannot assume, but still think this library is a good option.

### CODE REVIEW

**Comment by mgildea** [comment]
I don't think this is necessary.  Check out the following discussions on SO:

This describes the performance issues with using a Guid as primary key in regards to the default clustering key:
http://stackoverflow.com/questions/9111616/guids-vs-auto-incremented-ints

IF a guid is used it should be made partially sequential in the migration using newsequentialid() to help with this performance.  I'm not sure if this can be done using fluent api so It would have to be done in each user's migration; something I'm sure most would miss.

If there really are that many inserts/updates in your DB moving to a long as the key should be plenty:
http://stackoverflow.com/questions/24857449/should-i-use-an-int-or-a-long-for-the-primary-key-in-an-entity-framework-model

(another discussion points out that if you have a half million inserts per day to that table it would take 50,539,024,859 yrs to fill the table with a BIGINT identity(1,1) primary key)

There may be other valid reasons but the main arguments I have seen for using a guid as the key is when the key is generated outside of the database, or when you don't want primary keys to be predictable.

**Comment by gradu-kpmg** [comment]
Well in that case maybe long is the answer! I would be much comfortable with this than int.

**Comment by bilal-fazlani** [comment]
I agree with this. long seems better option.

**Comment by gradu-kpmg** [comment]
Hey the code in this branch is now updated for long. It's a non breaking change for upgrade purposes, but it would require a migration if someone upgrades... Also, all tests pass OK :)

**Comment by bilal-fazlani** [comment]
Merged

**Pull request merged**
