### PR TITLE
Change TypeExtensions.GetEntityType

### PR DESCRIPTION
**Pull request by LRFalk01**
Alter to use ObjectContext.GetObjectType. Removes a todo: improve this
recognition

### CODE REVIEW

**Comment by bilal-fazlani** [comment]
Thanks!

**Comment by bilal-fazlani** [comment]
That dint work. it crashed for some reason. reverted the change.

**Comment by LRFalk01** [comment]
I'm curious what the error was, if you still have it.

**Comment by bilal-fazlani** [comment]
It dint return any error. If i passed a proxy type to it, it returned the
same proxy type back. Which caused problems later in execution.

I want this method to return the actual type of entity even if I pass it a
proxy type.

**Pull request merged**
